export const mockCardData = [
  {
    missionToday: 'mission1',
    dDay: 6,
    expectedReward: 2000,
    title: '그라운드 제목 1',
    groundId: 1,
    isSuccess: null,
  },
  {
    missionToday: 'mission2',
    dDay: 3,
    expectedReward: 5000,
    title: '그라운드 제목 2',
    groundId: 2,
    isSuccess: null,
  },
  {
    missionToday: 'mission3',
    dDay: 1,
    expectedReward: 10000,
    title: '그라운드 제목 3',
    groundId: 3,
    isSuccess: null,
  },
  {
    missionToday: 'mission4',
    dDay: 4,
    expectedReward: 8000,
    title: '그라운드 제목 4',
    groundId: 4,
    isSuccess: null,
  },
  {
    missionToday: 'mission5',
    dDay: 7,
    expectedReward: 3000,
    title: '그라운드 제목 5',
    groundId: 5,
    isSuccess: null,
  },
  {
    missionToday: 'mission6',
    dDay: 2,
    expectedReward: 6000,
    title: '그라운드 제목 6',
    groundId: 6,
    isSuccess: null,
  },
  {
    missionToday: 'mission7',
    dDay: 5,
    expectedReward: 4000,
    title: '그라운드 제목 7',
    groundId: 7,
    isSuccess: null,
  },
  {
    missionToday: 'mission8',
    dDay: 6,
    expectedReward: 7000,
    title: '그라운드 제목 8',
    groundId: 8,
    isSuccess: null,
  },
  {
    missionToday: 'mission9',
    dDay: 4,
    expectedReward: 12000,
    title: '그라운드 제목 9',
    groundId: 9,
    isSuccess: null,
  },
  {
    missionToday: 'mission10',
    dDay: 3,
    expectedReward: 15000,
    title: '그라운드 제목 10',
    groundId: 10,
    isSuccess: null,
  },
];
