export const mockCardData = [
  {
    missionToday: 'mission1',
    dDay: 6,
    expectedReward: 2000,
    title: '그라운드 제목 1',
    groundId: 1,
    isSuccess: null,
  },
  {
    missionToday: 'mission2',
    dDay: 3,
    expectedReward: 5000,
    title: '그라운드 제목 2',
    groundId: 2,
    isSuccess: null,
  },
  {
    missionToday: 'mission3',
    dDay: 1,
    expectedReward: 10000,
    title: '그라운드 제목 3',
    groundId: 3,
    isSuccess: null,
  },
  {
    missionToday: 'mission4',
    dDay: 4,
    expectedReward: 8000,
    title: '그라운드 제목 4',
    groundId: 4,
    isSuccess: null,
  },
  {
    missionToday: 'mission5',
    dDay: 7,
    expectedReward: 3000,
    title: '그라운드 제목 5',
    groundId: 5,
    isSuccess: null,
  },
  {
    missionToday: 'mission6',
    dDay: 2,
    expectedReward: 6000,
    title: '그라운드 제목 6',
    groundId: 6,
    isSuccess: null,
  },
  {
    missionToday: 'mission7',
    dDay: 5,
    expectedReward: 4000,
    title: '그라운드 제목 7',
    groundId: 7,
    isSuccess: null,
  },
  {
    missionToday: 'mission8',
    dDay: 6,
    expectedReward: 7000,
    title: '그라운드 제목 8',
    groundId: 8,
    isSuccess: null,
  },
  {
    missionToday: 'mission9',
    dDay: 4,
    expectedReward: 12000,
    title: '그라운드 제목 9',
    groundId: 9,
    isSuccess: null,
  },
  {
    missionToday: 'mission10',
    dDay: 3,
    expectedReward: 15000,
    title: '그라운드 제목 10',
    groundId: 10,
    isSuccess: null,
  },
];

export const dummyUsers = [
  {
    username: 'user1',
    nickname: 'nickname1',
    success: true,
    missionScore: 1001,
  },
  {
    username: 'user2',
    nickname: 'nickname2',
    success: true,
    missionScore: 1002,
  },
  {
    username: 'user3',
    nickname: 'nickname3',
    success: true,
    missionScore: 1003,
  },
  {
    username: 'user4',
    nickname: 'nickname4',
    success: true,
    missionScore: 1004,
  },
  {
    username: 'user5',
    nickname: 'nickname5',
    success: false,
    missionScore: 1005,
  },
  {
    username: 'user6',
    nickname: 'nickname6',
    success: true,
    missionScore: 1006,
  },
  {
    username: 'user7',
    nickname: 'nickname7',
    success: true,
    missionScore: 1007,
  },
  {
    username: 'user8',
    nickname: 'nickname8',
    success: false,
    missionScore: 1008,
  },
  {
    username: 'user9',
    nickname: 'nickname9',
    success: true,
    missionScore: 1009,
  },
  {
    username: 'user10',
    nickname: 'nickname10',
    success: false,
    missionScore: 1010,
  },
  {
    username: 'user11',
    nickname: 'nickname11',
    success: true,
    missionScore: 1011,
  },
  {
    username: 'user12',
    nickname: 'nickname12',
    success: true,
    missionScore: 1012,
  },
  {
    username: 'user13',
    nickname: 'nickname13',
    success: true,
    missionScore: 1013,
  },
  {
    username: 'user14',
    nickname: 'nickname14',
    success: false,
    missionScore: 1014,
  },
  {
    username: 'user15',
    nickname: 'nickname15',
    success: false,
    missionScore: 1015,
  },
  {
    username: 'user16',
    nickname: 'nickname16',
    success: true,
    missionScore: 1016,
  },
  {
    username: 'user17',
    nickname: 'nickname17',
    success: true,
    missionScore: 1017,
  },
  {
    username: 'user18',
    nickname: 'nickname18',
    success: true,
    missionScore: 1018,
  },
  {
    username: 'user19',
    nickname: 'nickname19',
    success: true,
    missionScore: 1019,
  },
  {
    username: 'user20',
    nickname: 'nickname20',
    success: false,
    missionScore: 1020,
  },
];
